import { isAscii } from "./is_ascii.js";
import { isChar } from "./is_char.js";
import { isControl } from "./is_control.js";
import { isDigit } from "./is_digit.js";
import { isLatin1 } from "./is_latin1.js";
import { isLetter } from "./is_letter.js";
import { isLetterOrDigit } from "./is_letter_or_digit.js";
import { isLower } from "./is_lower.js";
import { isPunc } from "./is_punc.js";
import { isSpace } from "./is_space.js";
import { isSymbol } from "./is_symbol.js";
import { isUpper } from "./is_upper.js";
import { equalFold, simpleFold } from "./simple_fold.js";
import { toLower } from "./to_lower.js";
import { toUpper } from "./to_upper.js";
export { equalFold, isAscii, isChar, isControl, isDigit, isLatin1, isLetter, isLetterOrDigit, isLower, isPunc, isSpace, isSymbol, isUpper, simpleFold, toLower, toUpper, };
declare const _default: {
    equalFold: typeof equalFold;
    isAscii: typeof isAscii;
    isChar: typeof isChar;
    isControl: typeof isControl;
    isDigit: typeof isDigit;
    isLatin1: typeof isLatin1;
    isLetter: typeof isLetter;
    isLetterOrDigit: typeof isLetterOrDigit;
    isLower: typeof isLower;
    isPunc: typeof isPunc;
    isSpace: typeof isSpace;
    isSymbol: typeof isSymbol;
    simpleFold: typeof simpleFold;
    toLower: typeof toLower;
    toUpper: typeof toUpper;
};
export default _default;
