
tasks:
  install:
    description: Install the dependencies
    command: pnpm install
    local: true

  build:
    description: Transpile the typescript to javascript
    command: pnpm run build
    type: build
    local: true

  test:
    description: Run the vitest tests
    command: pnpm run test:run
    type: test
    deps:
      - lint

  lint:
    description: Lint the typescript
    command: pnpm run lint
    type: test

  fmt:
    description: Format the typescript
    command: pnpm run fmt
    local: true

  publish-dry:
    description: Dry publish the package
    command: pnpm publish --dry-run --access public --no-git-checks
    type: test 
    deps:
      - test