
tasks:
  test:
    description: Run the deno tests
    script: deno test -A --unstable-ffi
    type: test
    deps:
      - lint

  lint:
    description: Lint the typescript
    command: deno lint
    type: test
    options: 
      os: linux

  fmt:
    description: Format the typescript
    command: deno fmt
    local: true

  publish-dry:
    description: Dry publish the package
    command: deno publish --dry-run --allow-dirty
    deps:
      - test
   