
tasks:
  install:
    description: Install the dependencies
    command: pnpm install

  build:
    description: Transpile the typescript to javascript
    command: pnpm run build

  test:
    description: Run the vitest tests
    command: pnpm run test:run 

  lint:
    description: Lint the typescript
    command: pnpm run lint

  fmt:
    description: Format the typescript
    command: pnpm run fmt

  ci-build:
    description: Build the project
    command: pnpm run build
    deps:
      - install
      - build