name: ci

on:
  push:
  pull_request:
    

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - name: ci
        run: moon ci
        shell: bash
        