packages:
  # all packages in direct subdirs of packages/
  - 'bearz/*'
  # all packages in subdirs of components/
  - 'spawn/*'
  # exclude packages that are inside test directories
  - '!**/test/**'